// Seed data copied verbatim from PERIOFLOW_BUILD_SPEC.md.
// Used on first app load when storage is empty.

export const SEED_PAYERS = [
  { payer_id: 'delta_dental_ppo', name: 'Delta Dental PPO', plan_type: 'PPO', notes: 'Largest dental insurer. Extensive provider network.', portal_url: 'https://www.deltadental.com/' },
  { payer_id: 'delta_dental_premier', name: 'Delta Dental Premier', plan_type: 'Premier', notes: 'Higher reimbursement rates than PPO for OON.', portal_url: 'https://www.deltadental.com/' },
  { payer_id: 'metlife', name: 'MetLife Dental', plan_type: 'PPO', notes: 'Second largest dental insurer.', portal_url: 'https://www.metlife.com/dental/' },
  { payer_id: 'cigna', name: 'Cigna Dental', plan_type: 'PPO', notes: 'Often requires detailed narratives for perio.', portal_url: 'https://www.cigna.com/' },
  { payer_id: 'aetna', name: 'Aetna Dental', plan_type: 'PPO', notes: 'May require pre-authorization for surgical perio.', portal_url: 'https://www.aetna.com/' },
  { payer_id: 'united', name: 'UnitedHealthcare Dental', plan_type: 'PPO', notes: 'Part of UnitedHealth Group.', portal_url: 'https://www.uhc.com/' },
  { payer_id: 'guardian', name: 'Guardian Dental', plan_type: 'PPO', notes: 'Strong in employer group plans.', portal_url: 'https://www.guardianlife.com/dental-insurance' },
  { payer_id: 'humana', name: 'Humana Dental', plan_type: 'PPO', notes: 'Growing dental market share.', portal_url: 'https://www.humana.com/dental-insurance' },
  { payer_id: 'ameritas', name: 'Ameritas Dental', plan_type: 'PPO', notes: 'Common in small group plans.', portal_url: 'https://www.ameritas.com/' },
  { payer_id: 'principal', name: 'Principal Dental', plan_type: 'PPO', notes: 'Employer-sponsored plans.', portal_url: 'https://www.principal.com/' },
  { payer_id: 'bcbs', name: 'Blue Cross Blue Shield Dental', plan_type: 'PPO', notes: 'Plans and requirements vary by state.', portal_url: 'https://www.bcbs.com/' },
  { payer_id: 'lincoln', name: 'Lincoln Financial Dental', plan_type: 'PPO', notes: 'Common in employer benefits packages.', portal_url: 'https://www.lincolnfinancial.com/' },
]

export const SEED_CDT_CODES = [
  { code: 'D0120', category: 'diagnostic', description: 'Periodic oral evaluation (established patient)', requires_quadrant: false, requires_tooth_numbers: false, frequency_limit: 'Twice per 12 months', bundling_rules: '', common_documentation: ['Clinical notes'], common_denial_reasons: ['Frequency exceeded'] },
  { code: 'D0150', category: 'diagnostic', description: 'Comprehensive oral evaluation (new or established)', requires_quadrant: false, requires_tooth_numbers: false, frequency_limit: 'Once per 36 months for established patients', bundling_rules: '', common_documentation: ['Clinical notes', 'Medical history'], common_denial_reasons: ['Frequency exceeded', 'Duplicate of recent D0120'] },
  { code: 'D0180', category: 'diagnostic', description: 'Comprehensive periodontal evaluation (new or established)', requires_quadrant: false, requires_tooth_numbers: false, frequency_limit: 'Once per 36 months typically', bundling_rules: 'Cannot bill with D0150 same day', common_documentation: ['Full periodontal charting', 'Radiographs', 'Clinical notes documenting perio findings'], common_denial_reasons: ['Billed same day as D0150', 'Insufficient documentation of periodontal condition'] },
  { code: 'D0210', category: 'diagnostic', description: 'Full mouth series of radiographic images (intraoral)', requires_quadrant: false, requires_tooth_numbers: false, frequency_limit: 'Once per 36-60 months', bundling_rules: '', common_documentation: ['Images'], common_denial_reasons: ['Frequency exceeded', 'Recent FMX on file'] },
  { code: 'D0330', category: 'diagnostic', description: 'Panoramic radiographic image', requires_quadrant: false, requires_tooth_numbers: false, frequency_limit: 'Once per 36-60 months', bundling_rules: 'Some payers bundle with D0210', common_documentation: ['Image'], common_denial_reasons: ['Frequency exceeded'] },
  { code: 'D4341', category: 'non_surgical_perio', description: 'Scaling and root planing, 4+ teeth per quadrant', requires_quadrant: true, requires_tooth_numbers: false, frequency_limit: 'Once per 24-36 months per quadrant', bundling_rules: 'Cannot bill same day as D4210/D4211 same quadrant', common_documentation: ['Full periodontal charting with probing depths, BOP, recession', 'Periapical or bitewing radiographs', 'Written narrative with diagnosis, pocket depths, BOP%, bone loss', 'Date of last prophylaxis or perio maintenance'], common_denial_reasons: ['Narrative does not specify probing depths per quadrant', 'No radiographic evidence of bone loss', 'Frequency exceeded', 'Perio charting not included'] },
  { code: 'D4342', category: 'non_surgical_perio', description: 'Scaling and root planing, 1-3 teeth per quadrant', requires_quadrant: true, requires_tooth_numbers: false, frequency_limit: 'Once per 24-36 months per quadrant', bundling_rules: 'Cannot bill same day as D4210/D4211 same quadrant', common_documentation: ['Periodontal charting', 'Radiographs of affected area', 'Written narrative', 'Date of last prophylaxis'], common_denial_reasons: ['Insufficient documentation', 'Frequency exceeded'] },
  { code: 'D4346', category: 'non_surgical_perio', description: 'Scaling in presence of generalized moderate to severe gingival inflammation', requires_quadrant: false, requires_tooth_numbers: false, frequency_limit: 'Varies by payer', bundling_rules: 'Cannot bill with D4341/D4342 same date', common_documentation: ['Periodontal charting showing generalized inflammation', 'Clinical notes', 'Narrative justifying over prophylaxis'], common_denial_reasons: ['Insufficient documentation of inflammation', 'Billed with SRP same date'] },
  { code: 'D4355', category: 'non_surgical_perio', description: 'Full mouth debridement to enable evaluation and diagnosis', requires_quadrant: false, requires_tooth_numbers: false, frequency_limit: 'Once per lifetime typically', bundling_rules: 'Cannot bill with prophylaxis or SRP same day', common_documentation: ['Clinical notes documenting heavy calculus/debris preventing evaluation', 'Narrative'], common_denial_reasons: ['Billed with other cleaning codes same day', 'Frequency exceeded'] },
  { code: 'D4381', category: 'non_surgical_perio', description: 'Localized delivery of antimicrobial agents per tooth', requires_quadrant: false, requires_tooth_numbers: true, frequency_limit: 'Varies', bundling_rules: '', common_documentation: ['Periodontal charting', 'Clinical notes specifying tooth and agent used'], common_denial_reasons: ['Not covered by plan', 'Insufficient documentation'] },
  { code: 'D4210', category: 'surgical_perio', description: 'Gingivectomy or gingivoplasty, 4+ contiguous teeth per quadrant', requires_quadrant: true, requires_tooth_numbers: false, frequency_limit: 'Varies', bundling_rules: 'Not billable same day as D4341/D4342 or D4260/D4261 same quadrant. Requires 5-8mm pocketing.', common_documentation: ['Periodontal charting showing 5-8mm pockets', 'Radiographs', 'Narrative', 'Pre-op photos if available'], common_denial_reasons: ['Billed with SRP or osseous same day', 'Pocketing less than 5mm'] },
  { code: 'D4211', category: 'surgical_perio', description: 'Gingivectomy or gingivoplasty, 1-3 contiguous teeth per quadrant', requires_quadrant: true, requires_tooth_numbers: false, frequency_limit: 'Varies', bundling_rules: 'Same as D4210', common_documentation: ['Periodontal charting', 'Radiographs', 'Narrative'], common_denial_reasons: ['Same as D4210'] },
  { code: 'D4240', category: 'surgical_perio', description: 'Gingival flap procedure including root planing, 4+ contiguous teeth per quadrant', requires_quadrant: true, requires_tooth_numbers: false, frequency_limit: 'Varies', bundling_rules: '', common_documentation: ['Full periodontal charting', 'Full mouth series or periapical radiographs', 'Detailed surgical narrative', 'Prior SRP documentation'], common_denial_reasons: ['No prior SRP on record', 'Insufficient radiographic evidence', 'Pre-authorization not obtained'] },
  { code: 'D4241', category: 'surgical_perio', description: 'Gingival flap procedure including root planing, 1-3 contiguous teeth per quadrant', requires_quadrant: true, requires_tooth_numbers: false, frequency_limit: 'Varies', bundling_rules: '', common_documentation: ['Same as D4240'], common_denial_reasons: ['Same as D4240'] },
  { code: 'D4249', category: 'surgical_perio', description: 'Clinical crown lengthening', requires_quadrant: false, requires_tooth_numbers: true, frequency_limit: 'Varies', bundling_rules: 'Requires minimum 4-6 weeks before final crown prep', common_documentation: ['Radiographs', 'Clinical notes with tooth numbers', 'Narrative justifying procedure', 'Pre-op photos'], common_denial_reasons: ['Tooth numbers not specified', 'Considered cosmetic without justification'] },
  { code: 'D4260', category: 'surgical_perio', description: 'Osseous surgery, 4+ contiguous teeth per quadrant', requires_quadrant: true, requires_tooth_numbers: false, frequency_limit: 'Varies, typically once per area', bundling_rules: 'Cannot bill same day as D4210/D4211 same quadrant', common_documentation: ['Full periodontal charting', 'Full mouth series or periapical radiographs', 'Detailed narrative including bone loss measurements', 'Documentation of prior SRP', 'Pre-op photos if available'], common_denial_reasons: ['Quadrant not specified', 'No prior SRP documented', 'Insufficient radiographic evidence of bone loss', 'Pre-authorization required but not obtained', 'Full mouth series not included'] },
  { code: 'D4261', category: 'surgical_perio', description: 'Osseous surgery, 1-3 contiguous teeth per quadrant', requires_quadrant: true, requires_tooth_numbers: false, frequency_limit: 'Varies', bundling_rules: 'Same as D4260', common_documentation: ['Same as D4260'], common_denial_reasons: ['Same as D4260'] },
  { code: 'D4263', category: 'surgical_perio', description: 'Bone replacement graft, first site per quadrant', requires_quadrant: true, requires_tooth_numbers: true, frequency_limit: 'Varies', bundling_rules: 'Usually billed with flap or osseous surgery', common_documentation: ['Radiographs showing defect', 'Surgical narrative', 'Graft material documentation'], common_denial_reasons: ['Not covered by plan', 'Insufficient defect documentation'] },
  { code: 'D4264', category: 'surgical_perio', description: 'Bone replacement graft, each additional site per quadrant', requires_quadrant: true, requires_tooth_numbers: true, frequency_limit: 'Varies', bundling_rules: 'Must be billed with D4263', common_documentation: ['Same as D4263'], common_denial_reasons: ['Billed without D4263', 'Not covered'] },
  { code: 'D4273', category: 'surgical_perio', description: 'Autogenous connective tissue graft (soft tissue graft)', requires_quadrant: false, requires_tooth_numbers: true, frequency_limit: 'Varies', bundling_rules: '', common_documentation: ['Periodontal charting showing recession', 'Radiographs', 'Clinical photos showing recession', 'Narrative including Miller classification and functional/aesthetic justification'], common_denial_reasons: ['Considered cosmetic', 'Insufficient documentation of recession', 'Photos not included'] },
  { code: 'D4274', category: 'surgical_perio', description: 'Distal or proximal wedge procedure', requires_quadrant: true, requires_tooth_numbers: false, frequency_limit: 'Varies', bundling_rules: 'Inclusive to D4210/D4211', common_documentation: ['Periodontal charting', 'Radiographs', 'Narrative'], common_denial_reasons: ['Bundled with gingivectomy'] },
  { code: 'D4283', category: 'surgical_perio', description: 'Autogenous connective tissue graft, each additional contiguous tooth', requires_quadrant: false, requires_tooth_numbers: true, frequency_limit: 'Varies', bundling_rules: 'Must be billed with D4273', common_documentation: ['Same as D4273'], common_denial_reasons: ['Billed without D4273'] },
  { code: 'D4910', category: 'maintenance', description: 'Periodontal maintenance', requires_quadrant: false, requires_tooth_numbers: false, frequency_limit: 'Typically every 3-4 months, combined frequency with D1110', bundling_rules: 'Can only be billed after completed active perio therapy (SRP or surgery). Cannot substitute for D1110 without documented perio history.', common_documentation: ['Periodontal charting', 'Documentation of prior active perio treatment (SRP or surgery dates)', 'Clinical notes for current visit', 'Radiographs if taken'], common_denial_reasons: ['No documented history of prior active perio treatment', 'Frequency exceeded (combined with D1110)', 'Downgraded to D1110 by payer', 'Waiting period after SRP not met (usually 4-6 weeks)'] },
]

export const SEED_REQUIREMENTS = [
  {
    id: 'delta_dental_ppo__D4341',
    payer_id: 'delta_dental_ppo',
    cdt_code: 'D4341',
    required_documents: [
      { item: 'Full periodontal charting with probing depths, BOP, recession', priority: 'required', denial_risk: 'high' },
      { item: 'Periapical radiographs of affected quadrants', priority: 'required', denial_risk: 'high' },
      { item: 'Written narrative', priority: 'required', denial_risk: 'high' },
      { item: 'Date of last prophylaxis or perio maintenance', priority: 'recommended', denial_risk: 'medium' },
    ],
    narrative_elements: ['Diagnosis with AAP classification', 'Probing depths per quadrant', 'BOP percentage', 'Radiographic bone loss in mm', 'Justification for SRP vs prophylaxis'],
    watch_outs: ['Frequently denies if narrative does not specify pocket depths per quadrant', 'Must document probing depths exceed 4mm'],
    frequency_limit: 'Once per 24 months per quadrant',
    requires_pre_auth: false,
  },
  {
    id: 'delta_dental_ppo__D4260',
    payer_id: 'delta_dental_ppo',
    cdt_code: 'D4260',
    required_documents: [
      { item: 'Full mouth series of radiographs', priority: 'required', denial_risk: 'high' },
      { item: 'Full periodontal charting', priority: 'required', denial_risk: 'high' },
      { item: 'Detailed surgical narrative', priority: 'required', denial_risk: 'high' },
      { item: 'Documentation of prior SRP with dates', priority: 'required', denial_risk: 'high' },
      { item: 'Pre-operative photos', priority: 'recommended', denial_risk: 'low' },
    ],
    narrative_elements: ['Diagnosis with AAP staging', 'Bone loss measurements per site', 'Probing depths', 'BOP', 'Prior treatment history and response', 'Justification for surgical intervention'],
    watch_outs: ['Requires full mouth series, not just periapicals', 'Will deny without documented prior SRP', 'Quadrant must be specified on claim form'],
    frequency_limit: 'Typically once per area',
    requires_pre_auth: false,
  },
  {
    id: 'cigna__D4341',
    payer_id: 'cigna',
    cdt_code: 'D4341',
    required_documents: [
      { item: 'Full periodontal charting', priority: 'required', denial_risk: 'high' },
      { item: 'Radiographs (periapical or bitewing)', priority: 'required', denial_risk: 'high' },
      { item: 'Written narrative', priority: 'required', denial_risk: 'high' },
      { item: 'Full mouth series if available', priority: 'recommended', denial_risk: 'medium' },
    ],
    narrative_elements: ['Diagnosis', 'Probing depths with specific measurements', 'BOP', 'Bone loss', 'Treatment rationale'],
    watch_outs: ['Cigna often requests very detailed narratives', 'May request additional radiographs after submission'],
    frequency_limit: 'Once per 24 months per quadrant',
    requires_pre_auth: false,
  },
  {
    id: 'cigna__D4260',
    payer_id: 'cigna',
    cdt_code: 'D4260',
    required_documents: [
      { item: 'Full mouth series', priority: 'required', denial_risk: 'high' },
      { item: 'Full periodontal charting', priority: 'required', denial_risk: 'high' },
      { item: 'Detailed narrative', priority: 'required', denial_risk: 'high' },
      { item: 'Prior SRP documentation', priority: 'required', denial_risk: 'high' },
      { item: 'Pre-authorization', priority: 'required', denial_risk: 'high' },
    ],
    narrative_elements: ['Complete diagnosis', 'Bone defect descriptions per tooth', 'Prior treatment response', 'Surgical justification'],
    watch_outs: ['Pre-authorization required for osseous surgery', 'Frequently denies for insufficient radiographs', 'Very detailed narrative expected'],
    frequency_limit: 'Once per area',
    requires_pre_auth: true,
  },
  {
    id: 'aetna__D4341',
    payer_id: 'aetna',
    cdt_code: 'D4341',
    required_documents: [
      { item: 'Periodontal charting', priority: 'required', denial_risk: 'high' },
      { item: 'Periapical radiographs of affected quadrants', priority: 'required', denial_risk: 'high' },
      { item: 'Written narrative', priority: 'required', denial_risk: 'high' },
    ],
    narrative_elements: ['Diagnosis', 'Probing depths', 'BOP', 'Bone loss', 'Medical necessity statement'],
    watch_outs: ['Aetna requires 5-8mm pocketing documented for surgical codes', 'Check frequency limitations carefully'],
    frequency_limit: 'Once per 24 months per quadrant',
    requires_pre_auth: false,
  },
  {
    id: 'aetna__D4260',
    payer_id: 'aetna',
    cdt_code: 'D4260',
    required_documents: [
      { item: 'Full mouth series or periapicals', priority: 'required', denial_risk: 'high' },
      { item: 'Full periodontal charting', priority: 'required', denial_risk: 'high' },
      { item: 'Detailed surgical narrative', priority: 'required', denial_risk: 'high' },
      { item: 'Prior SRP documentation', priority: 'required', denial_risk: 'high' },
      { item: 'Pre-authorization may be required', priority: 'recommended', denial_risk: 'high' },
    ],
    narrative_elements: ['AAP classification', 'Bone loss per tooth', 'Probing depths', 'Prior treatment history', 'Surgical necessity'],
    watch_outs: ['Check if pre-authorization is required for the specific plan', 'Requires documentation of 5-8mm pocketing', 'D4210/D4211 not billable same day same quadrant'],
    frequency_limit: 'Varies by plan',
    requires_pre_auth: true,
  },
  {
    id: 'metlife__D4341',
    payer_id: 'metlife',
    cdt_code: 'D4341',
    required_documents: [
      { item: 'Periodontal charting', priority: 'required', denial_risk: 'high' },
      { item: 'Radiographs', priority: 'required', denial_risk: 'medium' },
      { item: 'Written narrative', priority: 'required', denial_risk: 'high' },
    ],
    narrative_elements: ['Diagnosis', 'Probing depths', 'BOP percentage', 'Bone loss'],
    watch_outs: ['MetLife may downgrade D4910 to D1110 if perio history not well documented'],
    frequency_limit: 'Once per 24 months per quadrant',
    requires_pre_auth: false,
  },
  {
    id: 'metlife__D4910',
    payer_id: 'metlife',
    cdt_code: 'D4910',
    required_documents: [
      { item: 'Current periodontal charting', priority: 'required', denial_risk: 'high' },
      { item: 'Documentation of prior active perio treatment (SRP or surgery dates)', priority: 'required', denial_risk: 'high' },
      { item: 'Clinical notes for current visit', priority: 'required', denial_risk: 'medium' },
    ],
    narrative_elements: ['History of periodontal treatment', 'Current pocket depths', 'Ongoing disease indicators', 'Maintenance interval justification'],
    watch_outs: ['MetLife frequently downgrades D4910 to D1110', 'Must have documented SRP or surgery dates', 'Combined frequency limit with D1110'],
    frequency_limit: 'Typically 3-4 per year, combined with D1110',
    requires_pre_auth: false,
  },
  {
    id: 'united__D4341',
    payer_id: 'united',
    cdt_code: 'D4341',
    required_documents: [
      { item: 'Periodontal charting', priority: 'required', denial_risk: 'high' },
      { item: 'Radiographs showing bone loss', priority: 'required', denial_risk: 'high' },
      { item: 'Written narrative', priority: 'required', denial_risk: 'high' },
    ],
    narrative_elements: ['Diagnosis', 'Probing depths', 'BOP', 'Bone loss description', 'Treatment rationale'],
    watch_outs: ['Verify plan covers perio at OON rates', 'Some UHC plans have very low OON maximums'],
    frequency_limit: 'Once per 24 months per quadrant',
    requires_pre_auth: false,
  },
  {
    id: 'guardian__D4341',
    payer_id: 'guardian',
    cdt_code: 'D4341',
    required_documents: [
      { item: 'Periodontal charting', priority: 'required', denial_risk: 'high' },
      { item: 'Radiographs', priority: 'required', denial_risk: 'medium' },
      { item: 'Written narrative', priority: 'required', denial_risk: 'high' },
    ],
    narrative_elements: ['Diagnosis', 'Probing depths', 'BOP', 'Bone loss'],
    watch_outs: ['Guardian typically processes OON claims smoothly with proper documentation'],
    frequency_limit: 'Once per 24 months per quadrant',
    requires_pre_auth: false,
  },
]

export const SEED_SETTINGS = {
  practice_name: 'PerioFlow Demo Practice',
  provider_name: 'Dr. Smith',
  practice_address: '123 Main St, Suite 100, San Francisco, CA 94102',
  practice_phone: '(555) 123-4567',
}
